### ISSUE TITLE
We've translated most of the blogs into Chinese

### ISSUE THREAD

**Issue by buginux** [terhechte/appventure-blog#19]
Hi, 
We are SwiftGG Chinese translation team, we are now translating high quality English swift blogs into Chinese to help native iOS developer better learning the swift language.

Thanks for your high quality blogs, and we've translated most of the blogs into Chinese. I'm wondering if you would like to add the translation link to the blog article. Or if you wish, you can tell us where to insert the link, then we can add the link ourselves and create a pull request.

Here are all the translated blogs: [http://swift.gg/tags/APPVENTURE/](http://swift.gg/tags/APPVENTURE/)

**Comment by terhechte** [comment]
Hey!

Thanks for your fantastic translations! I've just updated all my articles to provide a direct link to their translated counterparts. You can see the changes here:

https://github.com/terhechte/appventure-blog/commit/2b3ec3bedd309787d58fd508ae119294523c2861

Really awesome of you guys!

In the future, if you create more translations, you can simply copy & paste the translation header that I've used in all posts now and create a Pull Request and I'll merge it.

Fantastic work! Thanks!

Cheers,
Benedikt
