### ISSUE TITLE
Tuples as Arguments

### ISSUE THREAD

**Issue by xxx50236** [terhechte/appventure-blog#24]
Pass tuples as arguments to Enum is deprecated

**Comment by terhechte** [comment]
Yeah, I'm planning to transition all posts to Swift 3 once Xcode 8 / Swift 3 hit final.

**Comment by daveyostcom** [comment]
See my pull request.

**Comment by terhechte** [comment]
Thanks again for your PR. I totally forgot to close this issue :)
